### ISSUE TITLE
Contacted references appearing in "Initial Review" tab

### ISSUE THREAD

**Issue by kepaik** [MIT-LCP/physionet-build#1226]
I am assuming these are from Ken Pierce's workflow.

**Comment by tompollard** [comment]
As far as I can see, this issue occurs because our logic says: "Ignore any application in the workflow if (1) there is no review and (2) a reference has been contact. 

The bug occurs when:
1. a reviewer uses the new system and clicks "Process". This step creates a new "Credential Review" object to store the review (so a review now exists)
2. independently, a reviewer is invited using the management page.

The fix is to ignore applications that have completed the initial review checks (rather than ignoring applications that simply have a review object).
