### ISSUE TITLE
Identify whether a reference is a known reference and/or if they already have PhysioNet credentials

### ISSUE THREAD

**Issue by kepaik** [MIT-LCP/physionet-build#1233]
Maybe just a badge of some sort, to identify if a reference is an authenticated user.

Previously contacted references are less helpful, since we should still validate their identity, but is reassuring that they have already been cleared once at least.

**Comment by Lucas-Mc** [comment]
This could be tough as we would have to assume their reference email is the email they used for their account but seems like it could be helpful to cut down some applications. The known references is harder and less helpful since someone gets added as a known reference once they are contacted, even before the application is approved, so that could be misleading.

**Comment by kepaik** [comment]
Tying it to email is acceptable, and if we miss some that's fine. Still would provide peace of mind that we're contacting someone that has already accepted the DUA.

Known references is primarily a KPierce request, as it's useful for his workflow particularly when there are groups/classes with the same referrer.
