### ISSUE TITLE
Correct command to curl a restricted / credentialed dataset?

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#1434]
We currently list a `wget` command which allows downloading of a dataset, e.g. for MIMIC-IV:

`wget -r -N -c -np --user alistairewj --ask-password https://physionet.org/files/mimiciv/1.0/`

Is there an equivalent curl formulation? I tried the simplest equivalent:

`curl -u alistairewj:password https://physionet.org/files/mimiciv/1.0/core/admissions.csv.gz`

.. but this gives me a 403 forbidden. I assume that PhysioNet isn't using the authentication headers. Ultimately I managed to curl data by logging into to PhysioNet, starting a single download, copying the cookie/session tokens, and using those as arguments, ... but this seems a bit roundabout! Wondering if I missed something obvious? The command I ended up with was (with cookie/session redacted):

```sh
curl "https://physionet.org/files/mimiciv/1.0/core/admissions.csv.gz?download" \ 
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' \
-H 'Accept-Language: en-US,en;q=0.5' --compressed \
-H 'DNT: 1' \
-H 'Connection: keep-alive' \
-H 'Referer: https://physionet.org/content/mimiciv/1.0/' \
-H 'Cookie: csrftoken=helloiamatoken; sessionid=helloiamasession' \
-H 'Upgrade-Insecure-Requests: 1' \
-H 'Sec-Fetch-Dest: document' \
-H 'Sec-Fetch-Mode: navigate' \
-H 'Sec-Fetch-Site: same-origin' \
-H 'Sec-Fetch-User: ?1' \
-H 'TE: trailers'
```

**Comment by bemoody** [comment]
Yep, because most browsers implement HTTP auth in a way that is
confusing and user-unfriendly, most people don't understand how their
own browser works and therefore I think it's unwise to allow random UAs
to perform HTTP auth at all.

Second, if people want to create *new tools* (including things like
download scripts as well as libraries, GUIs, or web interfaces) for
accessing restricted PhysioNet data, I'm completely in favor of that,
but I would like for them to talk with us first and figure out how to
make those tools secure and compliant with our DUA rules.  Restricting
HTTP auth to specific UAs is an attempt to make people stop and think
about whether what they're trying to do is a good idea.

So, what's the tool you're trying to develop?  If it's useful and it's
done safely then we'd be happy to support it. ;)

**Comment by alistairewj** [comment]
Hah, nothing as elaborate as a tool. I was looking to download data directly from PhysioNet into a GCP bucket, and I can easily pipe cURL into gsutil to do so (without having the file go through my PC). Your decision makes sense about the HTTP auth, I only have a surface level understanding of it myself!

**Comment by bemoody** [comment]
I'll tell you a secret, then: wget also lets you send the output to a
pipe, just add "-O -".

**Comment by alistairewj** [comment]
An old dog something something... thanks!
