### ISSUE TITLE
Confusing "reminder" message

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#1760]
Today I received an email that reads:

```
From: PhysioNet Automated System <noreply@physionet.org>
Subject: Reminder - Revisions requested for project [...]

Project title: [...]
Submission ID: [...]
Submitting author: [...]

Dear Benjamin Moody,

Thank you for submitting your project entitled "[...]" to PhysioNet.

A summary of our standard set of editorial checks is listed below:

We ask that you address the following comments before we proceed:
Did you mean to resubmit this?

Once these comments have been addressed, please resubmit your
project.
```

However, I'm not the submitting author.  I didn't submit anything and I couldn't resubmit even if I wanted to.  I don't know what I'm being "reminded" of.

(Of course this message was intended for the submitting author, but the message is written as if it's directed at me personally.)

**Comment by briangow** [comment]
I agree, I discussed this with @tompollard  today after someone brought it to our attention. Thanks for raising the issue!

Do we want to keep the message like it is and only send it to the submitting author or revise it and send a message to all of the authors?

**Comment by alistairewj** [comment]
I'd only send it to the submitting author. No use sending a message to someone when they have no meaningful action to take from it.

**Comment by tompollard** [comment]
In general my preference is to copy emails to all co-authors because it is good for them to know what is happening with a project that they are co-authoring. 

Although they cannot take direct action (i.e. they can't edit the project themselves) they can still take action (e.g. email the submitting author to say that they are happy to take on some of the tasks outlined by the editors).

To avoid confusion, we could add some text to the non-submitting authors saying something like: "Only the submitting author is able to edit the project. You are receiving this message as a co-author and no direct action is required".

Saying this, I'd be happy with just sending to the submitting author (and it's probably easier to set this up!).

**Comment by alistairewj** [comment]
Counterpoint is having the submitting author receive a nagging e-mail to resubmit followed by their co-authors forwarding a very similar message to them gives me major Office Space vibes ;)

Since it's non-critical to submission I feel like we should be less noisy! The system already sends out a ton of e-mails during the publication process. Adding a no-op one is going to train people to ignore all of the messages.

**Comment by tompollard** [comment]
> Since it's non-critical to submission I feel like we should be less noisy! The system already sends out a ton of e-mails during the publication process. Adding a no-op one is going to train people to ignore all of the messages.

Fair enough, I'm good with sending to just the submitting author. As far as I can see, this issue is not directly related to reminder emails. It applies to decision emails too. e.g. this is the template for "revisions requested:"

https://github.com/MIT-LCP/physionet-build/blob/537e876a26b291d26cd13683dbe49db47925f623/physionet-django/notification/templates/notification/email/revise_submission_notify.html#L1-L19

**Comment by briangow** [comment]
I think this statement from the reminder email makes it particularly confusing to everyone except the submitting author: "Did you mean to resubmit this?". In sprit of minimizing the noise, I will set the reminder email to only go to the submitting author. 

Even with that, the phrasing in some of these emails could probably be improved. @tompollard would you like to propose some phrasing updates? Do we want to handle phrasing updates and sending reminders only to the submitting author in the same PR?

**Comment by tompollard** [comment]
> Do we want to handle phrasing updates and sending reminders only to the submitting author in the same PR?

I think it's best to deal with updates to phrasing later (though feel free to include some tweaks if something jumps out to you!).

**Comment by briangow** [comment]
I've created a PR to only send the reminder email to the submitting author. 

We can discuss the phrasing as a group and open another PR to address it after that. I'm fine with leaving this issue open until that is resolved.
