### ISSUE TITLE
Flickering modals that prevent the user clicking on buttons

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1764]
There is a bug with some of the modals that causes them to flicker and prevents the user from clicking on buttons. @briangow has noticed this too.

e.g. As an author, when I am trying to approve a project for publication at: https://physionet.org/projects/SLUG/submission/, I see the following modal:

![Screen Shot 2022-12-22 at 9 52 51 AM](https://user-images.githubusercontent.com/822601/209161272-bc7b862b-7c9b-4f44-bfb4-efd8128eba1a.png)

The approve button flickers and I am unable to click the "Approve publication" button.

**Comment by superryeti** [comment]
also found on on Delete Email confirmation Modal popup
[Modal Flikering.webm](https://user-images.githubusercontent.com/24412619/209365301-dd80f4d3-c2cf-409d-ab5e-157d595cb015.webm)

**Comment by superryeti** [comment]
If no one is working on this. i can take this over. @tompollard

**Comment by tompollard** [comment]
thanks @amitupreti we would definitely appreciate your help with this!

**Comment by superryeti** [comment]
Sounds great. I will get started. Thank you

**Comment by superryeti** [comment]
Interestingly, the flickering of modals seems to be happening because of use of this class `list-group-item` with a modal inside it.

So the two solutions discussed in the issue linked below was

1. Place the model outside the `<li>` with class `list-group-item` OR
2. Override the hover behaviour of the class `list-group-item`


```css
.list-group-item, .list-group-item:hover{ z-index: auto; }
```

The class `list-group-item` is used in total 51 places on the physionet model, out of that, i could find the similar conditions(i.e modal inside `<li>` with class `list-group-item`) in x places

1. manage_published_project.html - 2 places
2. active_submission_timeline.html - 1 place
3. author_list.html - 1 place(the issue Tom found)
4. edit_emails.html - 1 place

I kind of like solution 2 because it is quicK, less change on codebase, makes sure the flickering issue is fixed throughout the project and i could not find any code implementation that has complex stacking of modals or `<li>` elements.

But i might have missed something or maybe the project will evolve in future to include complex stacking. So solution1 seems like the right thing to do. 

For now i will go ahead and submit a PR with solution1 and wait for comments from @tompollard  on what he thinks might be the best solution( if solution2 is preferred, then i can discard the solution 1 and open another PR if needed with solution 2 or other recommendation.)


Related issue: https://github.com/twbs/bootstrap/issues/25206

**Comment by superryeti** [comment]
UPDATE: 

I initially thought that the first solution of placing the modal outside the `<li>` element would be the best approach, but upon further consideration, I realized that this solution might not be ideal in cases like `managed_published_project.html` where there are multiple `<li>` tags. In these cases, placing the modal outside the `<li>` elements could potentially disrupt the structure of the code, even though it wouldn't affect the UI.

As a result, I've decided to submit a PR with the second solution of overriding the hover behaviour of the list-group-item class. 
I will wait for @tompollard 's feedback and make changes if this doesn't sound like a good idea
