### ISSUE TITLE
Uploaded file content type

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#274]
If I:
- create a project (/projects/string-of-garbage/files/)
- upload a binary file (100s.dat)
- try to download the same file (/projects/string-of-garbage/files/100s.dat)

then the file is served with "Content-Type: text/html; charset=utf-8", despite the fact that the file is neither UTF-8, nor HTML.

**Comment by bemoody** [comment]
This is not fixed.  The content type (and the content itself) is coming from django, not from nginx (as you can see by running the demo server with manage.py.)

**Comment by elfeto** [comment]
Found a way to do this under Django. In theory, Django will only serve the files for protected/credentialed databases. Most of the databases files will be served by NGINX. I would have to do this by file extension because we serve the files by a http response.

If you know the file extensions and their supposed content type i can make that, or I will go with the extensions here: https://raw.githubusercontent.com/MIT-LCP/physionet-build/dev/deploy/custom-mime.types

**Comment by bemoody** [comment]
As a practical matter, we can't be slurping 4GB files anyway.  I
suspect the easiest way would be to use X-Accel-Redirect so nginx can
serve everyhing.

**Comment by bemoody** [comment]
(Side note, does the current impl even support range requests?!)

**Comment by elfeto** [comment]
So, I am doing the changes to send the content to nginx using X-Accel-Redirect. But then the content is served as "Content-Type: text/html; charset=utf-8" (is the default). I can do a check for the file extension before sending it to nginx and then change the charset with X-Accel-Charset.

In the other side-note, I am adding range requests.
