### ISSUE TITLE
Add download button next to each file?

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/physionet-build#310]
At the moment files can be downloaded one by one, but many browsers open text files on click, rather than opening a dialogue box to download them. This results in a bit of inconsistent UI interaction, e.g. in the [ecgcipa database](https://alpha.physionet.org/content/ecgcipa/) where clicking [addm.csv](https://alpha.physionet.org/static/published-projects/ecgcipa/files/addm.csv) opens the CSV in my browser but clicking [ecgcipa_metadata.docx](https://alpha.physionet.org/static/published-projects/ecgcipa/files/ecgcipa_metadata.docx) opens a dialogue box to download the data.

The worst case is a large text file like [adeg.csv - 25.6 MB](https://alpha.physionet.org/static/published-projects/ecgcipa/files/adeg.csv) being opened in the browser and slowing it down a bit.

I thought maybe adding a little download icon next to each file might help alleviate this and provide the user a consistent place to click to download files.

**Comment by bemoody** [comment]
This is something we need to seriously consider.  AFAIK it's currently inconsistent between public projects and restricted/unpublished projects.

As a general matter (by no means specific to PhysioNet), it can be annoying when:

- You want to *view* a file, and the browser won't let you do so, or makes you go through multiple clicks ("yes, I want to open this file; no, I want to open it in Atril, not GIMP") in order to do so... or worse, you're actually forced to save it to disk somewhere and open it in another program by hand.

- You want to *save* a file, and your browser doesn't give you a way to do so (or you don't know how.)

- You *think* that you want to view a file, without realizing that it's a 25 MB file that will make your browser throw a fit.  (Or else it's a binary data file but your browser still tries to display it as CP1252 text for some reason.)

How can we solve all of these problems, or at least strike a reasonable balance, and avoid making the interface overly complicated?  I have some ideas but I'd like to hear what other people think.

**Comment by alistairewj** [comment]
I like my button idea! Mockup:

![image](https://user-images.githubusercontent.com/1282676/58130354-d5701680-7be9-11e9-89d1-34b250cf98da.png)

**Comment by tompollard** [comment]
That looks good to me. What about having columns for view and download?

**Comment by bemoody** [comment]
"View" is what you'd get by clicking the file name, I think.

At the moment, clicking that link will either display the file as
plain text or try to download it (depending on the file, your browser,
and phase of the moon.)
