### ISSUE TITLE
Can't reset password while logged in?

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#312]
If I'm logged in but have forgotten my password, there doesn't seem to be any way for me to change it (unless I log out, which if I don't know my password is something I probably don't want to do.)

**Comment by tompollard** [comment]
We could add a note to the password reset page (https://alpha.physionet.org/settings/password/) to clarify the reset process. e.g.:

"If you do not know your current password, please use the following link to reset it: https://alpha.physionet.org/reset-password/"

**Comment by elfeto** [comment]
I added the reset link by email to the reset password page in the settings of the user. Also I automatically add the "primary" email using JS (If you have JS disabled, the form will be empty for you to add your primary email). I cant add this in the view, because there is no custom view, its a built in view by Django.
