### ISSUE TITLE
Topic keywords are case-sensitive

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#326]
In /search/topics/, keywords appear to be case-sensitive.  For example, searching for 'ecg' gives results (well, one result, anyway), but searching for 'ECG' does not.  Search terms should be case-folded at least, and perhaps normalized more aggressively.

**Comment by tompollard** [comment]
The search should be significantly improved (and the case issue fixed) in @lbulgarelli's next set of changes.

**Comment by tompollard** [comment]
Search has been improved in several steps and this issue is now resolved. The specific pull request for the case-sensitivity fix is: https://github.com/MIT-LCP/physionet-build/pull/336/files

The cause was differing syntax between our local and remote databases (needs some thought generally about how we handle this issue).

Example of a case-insensitive search: https://alpha.physionet.org/content/?topic=SKEleTAL&types=0&types=1&types=2&orderby=relevance&direction=desc
