### ISSUE TITLE
Allowing anonymous reviewers to see project previews

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/physionet-build#345]
Some journals require the data to be viewed by their reviewers before they will accept a paper. Authors are sometimes willing to publish the data first on PN, but occasionally they do not want to before their paper is published.

Should we build in a feature allowing reviewers to see the project preview of submitted projects? If so, we can work out the details. Remember: the reviewers must be anonymous to the data authors.

Possible methods:
1. A long random URL is generated for authors to send to the journal to directly view the preview. Simple, but nothing is tracked.
2. A long random URL is generated for authors to send to the journal, which can be used by the reviewers to make their PN accounts reviewers of the project.
3. We can assign PN accounts to be reviewers to submitted projects using the admin console. More work for us, requiring us to interface more with the journal/author, etc. May be most 'official' method if we decide to partner with journals.

Thoughts? Other solutions?

**Comment by bemoody** [comment]
"Long random URL" sounds easier from the POV of the guest reviewers.
Also it'd mean we don't have to worry about leaking the reviewer's
identity if we don't know who they are.

On the other hand, there is no way of controlling or even knowing who
has accessed that URL once it has been shared with the journal.  This
makes me slightly nervous.  It also definitely wouldn't work for
restricted-access projects.

It could also get weird when considering multiple revisions of the
project (does this long random URL point to the "current revision", or
to a snapshot of the project at one point in time?  can the URL only
be generated after the project has been "frozen"?)

Either way, users shouldn't have the ability to create a publicly
visible URL without the approval of PN editors.

Would the reviewers have strictly read-only access, or would we (for
example) want to allow them to make comments as well?

(I also touched on this briefly in issue #350)

**Comment by cx1111** [comment]
Good point about the safety and access (for protected projects). It may be good for editors to control this.

Just as a reminder, we have the ActiveProject model, one of which is created for each version. We create a PublishedProject from it when it becomes published, and delete the original ActiveProject object. So access would be given to each version.

One possible solution is that when a project is under submission, an admin can assign PN accounts 'reviewer' status, allowing them to view the project preview. When the submitting author submits the project for review, we should have a box asking whether the authors are expecting a journal to contact us for preview rights. Then they can send us emails or use some form to request access.

**Comment by tompollard** [comment]
For the reasons mentioned by @bemoody, I don't think we should provide authors with the ability to share unreviewed projects via an anonymous link (method 1).

My preference is for method 3, which essentially means building out the peer review functionality. A nice first nice step would be allowing the handling editor to assign users with the ability to view project content (similar to method 2).

**Comment by alistairewj** [comment]
I'll chime in with what is required by Scientific Data as I think it's a good basic functionality use case. It's essentially method 3 (accounts for reviewers), except the accounts are kept anonymous from the author's perspective. This would involve:

* Adding functionality for the author to generate a reviewer account with a randomly generated password
  * I think the author should be given the reviewer account credentials and its up to them to coordinate with the journal on how to access the data, rather than having the editor coordinate it
  * This reviewer account has permission to access the unpublished dataset (the preview and the ability to download files) - bonus points if the data can be accessed via GCP
  * Scientific Data has the ability to require signing of a data use agreement by reviewers. I don't think we can easily do on our end this since the one reviewer account will be shared by 2-3 reviewers.
* The unpublished dataset would need a DOI or accession number, as this is required in the interface, so we'd need to be able to "hold" a DOI for the dataset
* Upon final publication, the reviewer account is automatically deleted

**Comment by bemoody** [comment]
Thanks.  It's useful to hear about how other services have tried to
handle this issue.

From what you're describing, it sounds like:

- there's a single "reviewer account" that is shared by all reviewers
for a particular project

- that user account has no identity or contact information

- there's a shared password to access that account, which is given to
the author, and can't be changed (otherwise reviewers would be locking
each other out)

- that account has strictly read-only access (for example, we wouldn't
want to allow reviewers to add comments or annotations via that
account, as we wouldn't be able to attribute them - even to "anonymous
reviewer #1" - and they'd immediately be visible to all other
reviewers.)

Given all of that, I don't see any practical difference between a
"reviewer account" and a long secret URL that gives read-only access.
It would, however, be much more complicated for us to implement, since
the reviewer account basically behaves nothing like an ordinary PN
user account.

**Comment by tompollard** [comment]
@alistairewj is looking for a way to anonymously share data with reviewers for the MIMIC-CXR, so there's a need to implement this functionality. 

Turning around a bit on earlier comments, I think we've agreed that we are okay with projects being shared via an anonymous link, provided the link is generated by the editor for a temporary review period.

- After a project is submitted, a "generate private URL for external viewers" button is displayed to the project editor at: http://127.0.0.1:8000/console/submitted-projects/SHuKI1APLrwWCqxSQnSk/edit/
- If the button is clicked, a long, random URL is generated.
- Anyone with access to the URL is able to navigate to the private preview page (e.g. http://127.0.0.1:8000/projects/SHuKI1APLrwWCqxSQnSk/preview/?Admin=True).
- [nice to have]: The URL first directs the user to a Yes/No page where they must first agree to a set of usage terms (don't share data, etc). Perhaps reuse an existing data use agreement.
- It should be possible to deactivate the link from the page on which it was created.

**Comment by cx1111** [comment]
Would it be worthwhile to create a new app to manage external journal integration?

**Comment by tompollard** [comment]
I think journal integration would definitely belong in a new app, but this particular change (private links) wouldn't necessarily be part of that work. I'd just keep this change within the current apps.

**Comment by tompollard** [comment]
or a peer_review app!
