### ISSUE TITLE
Allow news items to be linked to published projects

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#368]
Add an optional field to the "create news" form that allows a news item to be linked to a published project. When a news item is linked to a published project, the news should be displayed on the project page (perhaps on the right hand side below the share links?). This functionality is required for posting updates/announcements on challenges.

**Comment by cx1111** [comment]
Let's think a bit more about this feature as it pertains to challenges.

We came up with this idea to make announcements for challenges, but it still feels like shoehorning to me. For every challenge, we will need to make multiple announcements.

- Do we really want to create a new news item and point it to the challenge every time we want to make a challenge announcement?
- Should every announcement be in the news? ie. some files were fixed/PHI was scrubbed.
- Should the fields of the News model be that tied to the dependencies of the challenges, rather than figuring out what makes sense in a news item?
- Big one: what if we want to display generic news for projects differently to how we display challenge announcements? Think about max items shown per page, style size and location, etc.

I feel like having a specific challenge announcements table, or even just an editable text field for each challenge, would be much cleaner.

**Comment by tompollard** [comment]
Thanks Chen. I don't think this is shoehorning...to me it feels like we're adapting the news/announcement functionality to make it useful! It becomes messy if we have two separate streams for handling the same thing.

- Do we really want to create a new news item and point it to the challenge every time we want to make a challenge announcement?

Yes, I think so. It seems better than having a separate interface for something that is basically a news/announcement item. If you're worried about the general news being overwhelmed with challenge updates, then we add an option to control priority/target for the news (e.g. "1: front page highlight", "2: project specific news").

- Should every announcement be in the news? ie. some files were fixed/PHI was scrubbed.

Same reply as above. Personally I think it's worth informing the whole community in both example cases.

- Should the fields of the News model be that tied to the dependencies of the challenges, rather than figuring out what makes sense in a news item?

Not sure I completely follow this point, but I think that it is useful to be able to associate news items with all projects in the same way (e.g. "we have released a new version of MIMIC" is displayed alongside the MIMIC project).

- Big one: what if we want to display generic news for projects differently to how we display challenge announcements? Think about max items shown per page, style size and location, etc.

If so, we build this into the our news/announcement functionality. It shouldn't be necessary to create a new news/announcement model to handle how the content is rendered. At most this would require an additional field or two in the news model.

**Comment by cx1111** [comment]
Also if news == challenge announcement, what about people who aren't admins who want to publish challenge projects? Are they barred from making announcements or will they be forced to email one of us to add a new item for them each time? 

It would be ok if Benjamin was the submitting author of every challenge project, but we also discussed having our collaborators as the authors instead of him. Also Tom wanted people to be able to host their own challenges.

**Comment by tompollard** [comment]
> Also if news == challenge announcement, what about people who aren't admins who want to publish challenge projects?

I'd say all user generated content should go through a review stage for posting (even if the creator is within the lab...it's useful to have a gatekeeper). 

At the moment we have very limited permission levels (just "not admin" vs "admin") and this is something we need to build out.

> Are they barred from making announcements or will they be forced to email one of us to add a new item for them each time?

Right now, people email Benjamin the announcement and then Benjamin posts it, so nothing changes. As a new feature, we can add functionality to allow users to create and submit announcements for posting.

**Comment by cx1111** [comment]
Thanks for the replies. Overall I can see pros and cons of both methods.

For the website switch this Wednesday, since we have limited time, I'll do something simple with LegacyProjects and some simple static announcement field for challenges. We can implement a better long term solution later.

**Comment by tompollard** [comment]
> I'll do something simple with LegacyProjects and some simple static announcement field for challenges

Is there a reason why adding a field to link news to project is more complicated? I'd prefer to spend time building this approach then hacking something we don't intend to keep. Will give you a call..
