### ISSUE TITLE
Support embargo period for published projects

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#457]
The idea needs more thought, but we would like to implement the ability for projects to be published under an embargo. Rough functionality would be:

- Editor clicks "Publish" button and is given the option to set an embargo period (e.g. setting length of time or a date when the embargo period finishes).
- The project is published as normal, except that access to files is restricted until the embargo period ends.

During the embargo period, we would like to be able to offer a subset of users with privileged access to the files (for example, users with a "subscriber" flag).

**Comment by tompollard** [comment]
Should we allow the author to request the embargo period? For example:

- during submission, the author requests a period in a similar way to a storage request
- editor either approves or declines the request
- if approved, the embargo is automatically set/applied on publication.

**Comment by bemoody** [comment]
The other context where we've talked about supporting embargoed data
is for the Challenge.  For the Challenge we would like to allow any
logged-in user to be able to access the data, provided that they agree
not to publish their own analyses until after the conclusion of the
challenge.

That is to say, they'd have to be logged in and click through an
agreement, but wouldn't need explicit approval (or need to be
credentialled) in order to do so.

We might also want to require them to formally register as challenge
participants, which might mean:
- they're required to specify an affiliation in their profile
- they're required to specify a list of their collaborators (which
might change during the course of the challenge)
and maybe other things.

After a fixed end date, the project becomes open access.

**Comment by alistairewj** [comment]
Summary of the discussion here

- add embargo with a duration (done in #1740)
- only the editor can add this currently
- would be nice for a user to be able to request it for a project they are submitting (not sure we have an issue for this - might be worth raising a new one if you agree @tompollard)
- @bemoody thoughts about allowing limited access to the challenge via the embargo feature seems like they could be a part of #1745 - which focuses about adding a feature for enabling access to certain subgroups.
