### ISSUE TITLE
Incorrect file size reported for MIMIC-CXR

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#792]
> The web page says the uncompressed size is 130 MB
> but when I try to download the files I get a progress meter saying
> eg. [ 4.4 GiB / 4.7 TiB ]  1% done
> and the expected size (4.7TB) keeps growing...
> Quite a bit more than 130 MB !!

The file sizes reported in the "Files" section for https://physionet.org/content/mimic-cxr/2.0.0/ are incorrect (e.g. "Total uncompressed size: 151.8 MB."). Presumably this is a result of our use of symlinks.

**Comment by bemoody** [comment]
The size according to 'du -Lbs' is 5129788391868.  That's not exactly
what get_tree_size would give you, but close enough.  Disk usage is an
inexact science :)

**Comment by alistairewj** [comment]
How long does `du -Lbs` take to run? If I remember correctly, I used symlinks to avoid the file size calculation taking ages and slowing down rendering of the page.

**Comment by bemoody** [comment]
Yeah.  I don't remember how long it takes, probably on the order of a
few minutes.  The Python code basically does the equivalent of 'du -b'
(without -L) to determine project size.  But it only does that while
the project is active - once a project is *published*, the total size
is stored in the database so it doesn't have to be calculated every
time.  So in this case, somebody just needs to go into the DB and
update that field with the correct value. :)

To better handle large projects in the future, what I'd like is to use
filesystem quota to track (and limit) project size - this is much more
efficient since the kernel keeps track of total usage for each group
ID, rather than having to iterate over all the files.

**Comment by alistairewj** [comment]
Bumping this - now that the project is published, would somebody mind venturing forth into the database and updating the file sizes?

File size of MIMIC-CXR in kilobytes: 5011060220
File size of MIMIC-CXR-JPG in kilobytes: 598683852

**Comment by tompollard** [comment]
Done! 

https://physionet.org/content/mimic-cxr/ -> 4.6 TB
https://physionet.org/content/mimic-cxr-jpg/ -> 557.6 GB
