### ISSUE TITLE
Blocking access to non-submitting authors for editing metadata and files

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/physionet-build#86]
Should decide whether non-submitting authors should be allowed to edit these things.

If not, need to block them by disabling certain fields/buttons (not from accessing the entire view itself).

**Comment by tnaumann** [comment]
I just encountered this issue. Our workaround was to start a Google Doc in which to edit the content collaboratively and then copy it into the project submission. I suspect the reason to allow only one author is to avoid the overhead of multi-user editing. Perhaps a Google Docs template with all the same fields could be provided so that anyone who runs into this issue can simply clone the Doc and get started with their collaborators that way prior to submission?

**Comment by tnaumann** [comment]
Alternatively, you could allow the submitting author to indicate a new submitting author from the active collaborators. This would allow users to effectively hand off the "edit lock" among themselves.
